#! /bin/bash
#PBS -N RNA_fastqc
#PBS -o /public/home/fudan_bio/anyu/RNA_seq/RNA_fastqc1.log
#PBS -j oe
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -q default

#软件路径
fastqc=/public/home/fudan_bio/anyu/miniconda3/envs/rnaseq/bin/fastqc
multiqc=/public/home/fudan_bio/anyu/miniconda3/envs/rnaseq/bin/multiqc

#工作路径及变量（每次需更改）
workdir=/public/home/fudan_bio/anyu/RNA_seq
datadir=/public/group_share_data/fudan_bio/anyu_lab/HuPI-Epilepsy/brainRNAseq/FASTQ/Sample_R20038555-pool1-EP01F
outdir=${workdir}/result/fastqc1
logfile=${workdir}/log/fastqclog1st.log

for file in $(ls ${datadir}/*.fastq.gz);do
	sample=`basename $file .fastq.gz`
	logtime=$(date "+%Y-%m-%d %H:%M:%S")
	echo "------------------------------" >> $logfile
	echo "LOG TIME: $logtime" >> $logfile
	echo "FILE NAME: $sample" >> $logfile
	echo "------------------------------" >> $logfile
	$fastqc $file -o ${outdir} 2>>${logfile}
	echo "\n" >>${logfile}
done

$multiqc ${outdir} -o ${outdir}


