name: scrnaseq-snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - snakemake=7.32
  - scanpy=1.9
  - anndata=0.8
  - pandas=2.0
  - numpy=1.24
  - matplotlib=3.7
  - seaborn=0.12
  - python-igraph=0.10
  - leidenalg=0.9
  - umap-learn=0.5
  - scikit-learn=1.2
  - pip
  - pip:
    - scrublet
    - gseapy