#!/bin/bash

#PBS -N run_vcf-genotyping
#PBS -j oe
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00
#PBS -q default

# 软件执行路径
gatk=$HOME/software/anaconda/anaconda3/envs/wes-analysis/bin/gatk

# 工作路径
workdir=$HOME/ASD_prof.AN
outdir=${workdir}/results/20201215

# 批量执行变量: $vcfgroup

# 其他变量
refgenome=$HOME/ASD_prof.AN/data/reference_genome/gatk-hg19/ucsc.hg19.fa

# 程序执行时间及日志
logtime=$(date "+%Y-%m-%d %H:%M:%S")
logfile=${workdir}/logs/20201215/run_vcf-genotyping_${vcfgroup}.log
echo "------------------------------" >> $logfile
echo "LOG TIME: $logtime" >> $logfile
echo "------------------------------" >> $logfile

## 执行内容
sampleGVCFs="" 2>>$logfile
for i in $(ls ${workdir}/data/ASD_WESdata_20201215/FASTQ/${vcfgroup}/); do
    sampleID=${i/Sample_/}
    gvcf=${outdir}/gvcf_output/${sampleID}_g.vcf.gz
    sampleGVCFs=${sampleGVCFs}"-V $gvcf "
done 2>>$logfile
$gatk CombineGVCFs -R $refgenome $sampleGVCFs -O ${outdir}/gatk_output/${vcfgroup}.g.vcf.gz 2>>$logfile
$gatk GenotypeGVCFs -R $refgenome -V ${outdir}/gatk_output/${vcfgroup}.g.vcf.gz \
    -O ${outdir}/vcf_output/${vcfgroup}_raw.vcf.gz 2>>$logfile
rm ${outdir}/gatk_output/${vcfgroup}.g.vcf.gz 2>>$logfile

# 执行日志结束
echo "" >> $logfile

# END
